- name: Create Backend Directory
  file:
    path: /home/ubuntu/backend
    state: directory
- name: Copy from CircleCI
  copy:
    src: /root/project/backend/dist.tar.gz
    dest: /home/ubuntu/backend

- name: Run pm2
  become: true
  args:
    warn: false
  shell: |
    cd /home/ubuntu/backend
    tar -xvf artifacts.tar.gz
    npm i
    npm run build
    pm2 start npm --name backend -- start