- name: Create Backend Directory
  file:
    path: /home/ubuntu/backend
    state: directory
- name: Copy from CircleCI
  copy:
    src: /home/dist.tar.gz
    dest: /home/ubuntu/backend

- name: Run pm2
  become: true
  shell: |
    cd /home/ubuntu/backend 
    tar xzvf dist.tar.gz 
    ls -lah
    pm2 start npm --name backend -- start