- name: Create Backend Directory
  file:
    path: /home/ubuntu/backend
    state: directory
- name: Copy from CircleCI
  copy:
    src: /root/project/backend/
    dest: /home/ubuntu/backend

- name: Run pm2
  become: true
  shell: |
    cd /home/ubuntu/backend 
    npm i
    npm run build
    ls -lah
    pm2 start npm --name backend -- start